name: 01 - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
  - cron: 0 2 * * 3,6

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build the docker image
      run: docker build . --file Dockerfile --no-cache --tag elixir-rocky:$(date +%s)
