name: 01 - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      no_cache:
        description: 'Force rebuild without cache'
        required: false
        type: boolean
        default: true
  schedule:
  - cron: 0 2 * * 3,6

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build the docker image
      run: |
        # Determine cache strategy
        if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.no_cache }}" = "false" ]; then
          CACHE_FLAG=""
          echo "Building with cache..."
        else
          CACHE_FLAG="--no-cache"
          echo "Building without cache..."
        fi
        
        docker build . --file Dockerfile $CACHE_FLAG --tag elixir-rocky:$(date +%s)
