name: cd

on:
  release:
    types: [ published ]

jobs:

  build:
    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to dockerhub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Get current tag
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build and push with latest
      run: docker build . --file Dockerfile --no-cache --tag thomis/elixir-rocky:${{ env.tag }} --tag thomis/elixir-rocky:latest

    - name: Push the tagged docker image
      run: docker push thomis/elixir-rocky:${{ env.tag }}

    - name: Push the latest docker image
      run: docker push thomis/elixir-rocky:latest
