name: cd2

on:
  release:
    types: [ published ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up qemu
      uses: docker/setup-qemu-action@v2

    - name: Set up docker bildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current tag
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build and push with latest
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: thomis/elixir-rocky:latest

    - name: Build and push with current tag
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: thomis/elixir-rocky:${{ env.tag }}
