name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
  - cron: 0 2 * * 1,3,5,6

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the docker image
      run: docker build . --file Dockerfile --no-cache --tag elixir-rocky:$(date +%s)
